server {
    listen 80;

    # 1. Servir el Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy Inverso: Lo que vaya a /api lo manda al contenedor 'backend'
    location /api/ {
        # 'backend' es el nombre del servicio en el docker-compose
        proxy_pass http://backend:3000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}